version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/specs/assets/sinatra-app"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  versioning-strategy: increase
