// Code generated by counterfeiter. DO NOT EDIT.
package migratefakes

import (
	"sync"
)

type FakeClient struct {
	BindServiceStub        func(appName, serviceName string) error
	bindServiceMutex       sync.RWMutex
	bindServiceArgsForCall []struct {
		appName     string
		serviceName string
	}
	bindServiceReturns struct {
		result1 error
	}
	bindServiceReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteAppStub        func(appName string) error
	deleteAppMutex       sync.RWMutex
	deleteAppArgsForCall []struct {
		appName string
	}
	deleteAppReturns struct {
		result1 error
	}
	deleteAppReturnsOnCall map[int]struct {
		result1 error
	}
	DumpLogsStub        func(appName string)
	dumpLogsMutex       sync.RWMutex
	dumpLogsArgsForCall []struct {
		appName string
	}
	PushAppStub        func(path, appName string) error
	pushAppMutex       sync.RWMutex
	pushAppArgsForCall []struct {
		path    string
		appName string
	}
	pushAppReturns struct {
		result1 error
	}
	pushAppReturnsOnCall map[int]struct {
		result1 error
	}
	RenameServiceStub        func(oldName, newName string) error
	renameServiceMutex       sync.RWMutex
	renameServiceArgsForCall []struct {
		oldName string
		newName string
	}
	renameServiceReturns struct {
		result1 error
	}
	renameServiceReturnsOnCall map[int]struct {
		result1 error
	}
	RunTaskStub        func(appName, command string) error
	runTaskMutex       sync.RWMutex
	runTaskArgsForCall []struct {
		appName string
		command string
	}
	runTaskReturns struct {
		result1 error
	}
	runTaskReturnsOnCall map[int]struct {
		result1 error
	}
	StartAppStub        func(appName string) error
	startAppMutex       sync.RWMutex
	startAppArgsForCall []struct {
		appName string
	}
	startAppReturns struct {
		result1 error
	}
	startAppReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeClient) BindService(appName string, serviceName string) error {
	fake.bindServiceMutex.Lock()
	ret, specificReturn := fake.bindServiceReturnsOnCall[len(fake.bindServiceArgsForCall)]
	fake.bindServiceArgsForCall = append(fake.bindServiceArgsForCall, struct {
		appName     string
		serviceName string
	}{appName, serviceName})
	fake.recordInvocation("BindService", []interface{}{appName, serviceName})
	fake.bindServiceMutex.Unlock()
	if fake.BindServiceStub != nil {
		return fake.BindServiceStub(appName, serviceName)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.bindServiceReturns.result1
}

func (fake *FakeClient) BindServiceCallCount() int {
	fake.bindServiceMutex.RLock()
	defer fake.bindServiceMutex.RUnlock()
	return len(fake.bindServiceArgsForCall)
}

func (fake *FakeClient) BindServiceArgsForCall(i int) (string, string) {
	fake.bindServiceMutex.RLock()
	defer fake.bindServiceMutex.RUnlock()
	return fake.bindServiceArgsForCall[i].appName, fake.bindServiceArgsForCall[i].serviceName
}

func (fake *FakeClient) BindServiceReturns(result1 error) {
	fake.BindServiceStub = nil
	fake.bindServiceReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) BindServiceReturnsOnCall(i int, result1 error) {
	fake.BindServiceStub = nil
	if fake.bindServiceReturnsOnCall == nil {
		fake.bindServiceReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.bindServiceReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) DeleteApp(appName string) error {
	fake.deleteAppMutex.Lock()
	ret, specificReturn := fake.deleteAppReturnsOnCall[len(fake.deleteAppArgsForCall)]
	fake.deleteAppArgsForCall = append(fake.deleteAppArgsForCall, struct {
		appName string
	}{appName})
	fake.recordInvocation("DeleteApp", []interface{}{appName})
	fake.deleteAppMutex.Unlock()
	if fake.DeleteAppStub != nil {
		return fake.DeleteAppStub(appName)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.deleteAppReturns.result1
}

func (fake *FakeClient) DeleteAppCallCount() int {
	fake.deleteAppMutex.RLock()
	defer fake.deleteAppMutex.RUnlock()
	return len(fake.deleteAppArgsForCall)
}

func (fake *FakeClient) DeleteAppArgsForCall(i int) string {
	fake.deleteAppMutex.RLock()
	defer fake.deleteAppMutex.RUnlock()
	return fake.deleteAppArgsForCall[i].appName
}

func (fake *FakeClient) DeleteAppReturns(result1 error) {
	fake.DeleteAppStub = nil
	fake.deleteAppReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) DeleteAppReturnsOnCall(i int, result1 error) {
	fake.DeleteAppStub = nil
	if fake.deleteAppReturnsOnCall == nil {
		fake.deleteAppReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteAppReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) DumpLogs(appName string) {
	fake.dumpLogsMutex.Lock()
	fake.dumpLogsArgsForCall = append(fake.dumpLogsArgsForCall, struct {
		appName string
	}{appName})
	fake.recordInvocation("DumpLogs", []interface{}{appName})
	fake.dumpLogsMutex.Unlock()
	if fake.DumpLogsStub != nil {
		fake.DumpLogsStub(appName)
	}
}

func (fake *FakeClient) DumpLogsCallCount() int {
	fake.dumpLogsMutex.RLock()
	defer fake.dumpLogsMutex.RUnlock()
	return len(fake.dumpLogsArgsForCall)
}

func (fake *FakeClient) DumpLogsArgsForCall(i int) string {
	fake.dumpLogsMutex.RLock()
	defer fake.dumpLogsMutex.RUnlock()
	return fake.dumpLogsArgsForCall[i].appName
}

func (fake *FakeClient) PushApp(path string, appName string) error {
	fake.pushAppMutex.Lock()
	ret, specificReturn := fake.pushAppReturnsOnCall[len(fake.pushAppArgsForCall)]
	fake.pushAppArgsForCall = append(fake.pushAppArgsForCall, struct {
		path    string
		appName string
	}{path, appName})
	fake.recordInvocation("PushApp", []interface{}{path, appName})
	fake.pushAppMutex.Unlock()
	if fake.PushAppStub != nil {
		return fake.PushAppStub(path, appName)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.pushAppReturns.result1
}

func (fake *FakeClient) PushAppCallCount() int {
	fake.pushAppMutex.RLock()
	defer fake.pushAppMutex.RUnlock()
	return len(fake.pushAppArgsForCall)
}

func (fake *FakeClient) PushAppArgsForCall(i int) (string, string) {
	fake.pushAppMutex.RLock()
	defer fake.pushAppMutex.RUnlock()
	return fake.pushAppArgsForCall[i].path, fake.pushAppArgsForCall[i].appName
}

func (fake *FakeClient) PushAppReturns(result1 error) {
	fake.PushAppStub = nil
	fake.pushAppReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) PushAppReturnsOnCall(i int, result1 error) {
	fake.PushAppStub = nil
	if fake.pushAppReturnsOnCall == nil {
		fake.pushAppReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.pushAppReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) RenameService(oldName string, newName string) error {
	fake.renameServiceMutex.Lock()
	ret, specificReturn := fake.renameServiceReturnsOnCall[len(fake.renameServiceArgsForCall)]
	fake.renameServiceArgsForCall = append(fake.renameServiceArgsForCall, struct {
		oldName string
		newName string
	}{oldName, newName})
	fake.recordInvocation("RenameService", []interface{}{oldName, newName})
	fake.renameServiceMutex.Unlock()
	if fake.RenameServiceStub != nil {
		return fake.RenameServiceStub(oldName, newName)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.renameServiceReturns.result1
}

func (fake *FakeClient) RenameServiceCallCount() int {
	fake.renameServiceMutex.RLock()
	defer fake.renameServiceMutex.RUnlock()
	return len(fake.renameServiceArgsForCall)
}

func (fake *FakeClient) RenameServiceArgsForCall(i int) (string, string) {
	fake.renameServiceMutex.RLock()
	defer fake.renameServiceMutex.RUnlock()
	return fake.renameServiceArgsForCall[i].oldName, fake.renameServiceArgsForCall[i].newName
}

func (fake *FakeClient) RenameServiceReturns(result1 error) {
	fake.RenameServiceStub = nil
	fake.renameServiceReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) RenameServiceReturnsOnCall(i int, result1 error) {
	fake.RenameServiceStub = nil
	if fake.renameServiceReturnsOnCall == nil {
		fake.renameServiceReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.renameServiceReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) RunTask(appName string, command string) error {
	fake.runTaskMutex.Lock()
	ret, specificReturn := fake.runTaskReturnsOnCall[len(fake.runTaskArgsForCall)]
	fake.runTaskArgsForCall = append(fake.runTaskArgsForCall, struct {
		appName string
		command string
	}{appName, command})
	fake.recordInvocation("RunTask", []interface{}{appName, command})
	fake.runTaskMutex.Unlock()
	if fake.RunTaskStub != nil {
		return fake.RunTaskStub(appName, command)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.runTaskReturns.result1
}

func (fake *FakeClient) RunTaskCallCount() int {
	fake.runTaskMutex.RLock()
	defer fake.runTaskMutex.RUnlock()
	return len(fake.runTaskArgsForCall)
}

func (fake *FakeClient) RunTaskArgsForCall(i int) (string, string) {
	fake.runTaskMutex.RLock()
	defer fake.runTaskMutex.RUnlock()
	return fake.runTaskArgsForCall[i].appName, fake.runTaskArgsForCall[i].command
}

func (fake *FakeClient) RunTaskReturns(result1 error) {
	fake.RunTaskStub = nil
	fake.runTaskReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) RunTaskReturnsOnCall(i int, result1 error) {
	fake.RunTaskStub = nil
	if fake.runTaskReturnsOnCall == nil {
		fake.runTaskReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.runTaskReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) StartApp(appName string) error {
	fake.startAppMutex.Lock()
	ret, specificReturn := fake.startAppReturnsOnCall[len(fake.startAppArgsForCall)]
	fake.startAppArgsForCall = append(fake.startAppArgsForCall, struct {
		appName string
	}{appName})
	fake.recordInvocation("StartApp", []interface{}{appName})
	fake.startAppMutex.Unlock()
	if fake.StartAppStub != nil {
		return fake.StartAppStub(appName)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.startAppReturns.result1
}

func (fake *FakeClient) StartAppCallCount() int {
	fake.startAppMutex.RLock()
	defer fake.startAppMutex.RUnlock()
	return len(fake.startAppArgsForCall)
}

func (fake *FakeClient) StartAppArgsForCall(i int) string {
	fake.startAppMutex.RLock()
	defer fake.startAppMutex.RUnlock()
	return fake.startAppArgsForCall[i].appName
}

func (fake *FakeClient) StartAppReturns(result1 error) {
	fake.StartAppStub = nil
	fake.startAppReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) StartAppReturnsOnCall(i int, result1 error) {
	fake.StartAppStub = nil
	if fake.startAppReturnsOnCall == nil {
		fake.startAppReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.startAppReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.bindServiceMutex.RLock()
	defer fake.bindServiceMutex.RUnlock()
	fake.deleteAppMutex.RLock()
	defer fake.deleteAppMutex.RUnlock()
	fake.dumpLogsMutex.RLock()
	defer fake.dumpLogsMutex.RUnlock()
	fake.pushAppMutex.RLock()
	defer fake.pushAppMutex.RUnlock()
	fake.renameServiceMutex.RLock()
	defer fake.renameServiceMutex.RUnlock()
	fake.runTaskMutex.RLock()
	defer fake.runTaskMutex.RUnlock()
	fake.startAppMutex.RLock()
	defer fake.startAppMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
