package app

import (
	_ "embed"
	"fmt"
	"os"
	"path/filepath"
)

var (
	// migration-app.zip is generated by the top-level ./scripts/build-assets script
	//go:embed migration-app.zip
	migrationApp []byte
	//go:embed manifest.yml
	appManifest []byte
)

type Extractor struct{}

func NewExtractor() Extractor {
	return Extractor{}
}

func (Extractor) Unpack(directoryPath string) error {
	appPath := filepath.Join(directoryPath, "migration-app.zip")
	if err := os.WriteFile(appPath, migrationApp, 0o444); err != nil {
		return fmt.Errorf("failed to extract migration-app.zip to %q: %w", appPath, err)
	}

	manifestPath := filepath.Join(directoryPath, "manifest.yml")
	if err := os.WriteFile(manifestPath, appManifest, 0444); err != nil {
		return fmt.Errorf("failed to extract migration app manifest.yml to %q: %w", manifestPath, err)
	}

	return nil
}
