// Code generated by counterfeiter. DO NOT EDIT.
package migratefakes

import (
	"sync"

	"github.com/pivotal-cf/mysql-cli-plugin/mysql-tools/migrate"
)

type FakeUnpacker struct {
	UnpackStub        func(string) error
	unpackMutex       sync.RWMutex
	unpackArgsForCall []struct {
		arg1 string
	}
	unpackReturns struct {
		result1 error
	}
	unpackReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeUnpacker) Unpack(arg1 string) error {
	fake.unpackMutex.Lock()
	ret, specificReturn := fake.unpackReturnsOnCall[len(fake.unpackArgsForCall)]
	fake.unpackArgsForCall = append(fake.unpackArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.UnpackStub
	fakeReturns := fake.unpackReturns
	fake.recordInvocation("Unpack", []interface{}{arg1})
	fake.unpackMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeUnpacker) UnpackCallCount() int {
	fake.unpackMutex.RLock()
	defer fake.unpackMutex.RUnlock()
	return len(fake.unpackArgsForCall)
}

func (fake *FakeUnpacker) UnpackCalls(stub func(string) error) {
	fake.unpackMutex.Lock()
	defer fake.unpackMutex.Unlock()
	fake.UnpackStub = stub
}

func (fake *FakeUnpacker) UnpackArgsForCall(i int) string {
	fake.unpackMutex.RLock()
	defer fake.unpackMutex.RUnlock()
	argsForCall := fake.unpackArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeUnpacker) UnpackReturns(result1 error) {
	fake.unpackMutex.Lock()
	defer fake.unpackMutex.Unlock()
	fake.UnpackStub = nil
	fake.unpackReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeUnpacker) UnpackReturnsOnCall(i int, result1 error) {
	fake.unpackMutex.Lock()
	defer fake.unpackMutex.Unlock()
	fake.UnpackStub = nil
	if fake.unpackReturnsOnCall == nil {
		fake.unpackReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.unpackReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeUnpacker) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.unpackMutex.RLock()
	defer fake.unpackMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeUnpacker) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ migrate.Unpacker = new(FakeUnpacker)
