// Code generated by counterfeiter. DO NOT EDIT.
package pluginfakes

import (
	"sync"

	"github.com/pivotal-cf/mysql-cli-plugin/mysql-tools/migrate"
	"github.com/pivotal-cf/mysql-cli-plugin/mysql-tools/plugin"
)

type FakeMigrator struct {
	CheckServiceExistsStub        func(string) error
	checkServiceExistsMutex       sync.RWMutex
	checkServiceExistsArgsForCall []struct {
		arg1 string
	}
	checkServiceExistsReturns struct {
		result1 error
	}
	checkServiceExistsReturnsOnCall map[int]struct {
		result1 error
	}
	ConfigureServiceInstanceStub        func(string) error
	configureServiceInstanceMutex       sync.RWMutex
	configureServiceInstanceArgsForCall []struct {
		arg1 string
	}
	configureServiceInstanceReturns struct {
		result1 error
	}
	configureServiceInstanceReturnsOnCall map[int]struct {
		result1 error
	}
	CreateAndConfigureServiceInstanceStub        func(string, string) error
	createAndConfigureServiceInstanceMutex       sync.RWMutex
	createAndConfigureServiceInstanceArgsForCall []struct {
		arg1 string
		arg2 string
	}
	createAndConfigureServiceInstanceReturns struct {
		result1 error
	}
	createAndConfigureServiceInstanceReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteServiceInstanceOnErrorStub        func(string) error
	deleteServiceInstanceOnErrorMutex       sync.RWMutex
	deleteServiceInstanceOnErrorArgsForCall []struct {
		arg1 string
	}
	deleteServiceInstanceOnErrorReturns struct {
		result1 error
	}
	deleteServiceInstanceOnErrorReturnsOnCall map[int]struct {
		result1 error
	}
	MigrateDataStub        func(migrate.MigrateOptions) error
	migrateDataMutex       sync.RWMutex
	migrateDataArgsForCall []struct {
		arg1 migrate.MigrateOptions
	}
	migrateDataReturns struct {
		result1 error
	}
	migrateDataReturnsOnCall map[int]struct {
		result1 error
	}
	RenameServiceInstancesStub        func(string, string) error
	renameServiceInstancesMutex       sync.RWMutex
	renameServiceInstancesArgsForCall []struct {
		arg1 string
		arg2 string
	}
	renameServiceInstancesReturns struct {
		result1 error
	}
	renameServiceInstancesReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeMigrator) CheckServiceExists(arg1 string) error {
	fake.checkServiceExistsMutex.Lock()
	ret, specificReturn := fake.checkServiceExistsReturnsOnCall[len(fake.checkServiceExistsArgsForCall)]
	fake.checkServiceExistsArgsForCall = append(fake.checkServiceExistsArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("CheckServiceExists", []interface{}{arg1})
	fake.checkServiceExistsMutex.Unlock()
	if fake.CheckServiceExistsStub != nil {
		return fake.CheckServiceExistsStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.checkServiceExistsReturns
	return fakeReturns.result1
}

func (fake *FakeMigrator) CheckServiceExistsCallCount() int {
	fake.checkServiceExistsMutex.RLock()
	defer fake.checkServiceExistsMutex.RUnlock()
	return len(fake.checkServiceExistsArgsForCall)
}

func (fake *FakeMigrator) CheckServiceExistsCalls(stub func(string) error) {
	fake.checkServiceExistsMutex.Lock()
	defer fake.checkServiceExistsMutex.Unlock()
	fake.CheckServiceExistsStub = stub
}

func (fake *FakeMigrator) CheckServiceExistsArgsForCall(i int) string {
	fake.checkServiceExistsMutex.RLock()
	defer fake.checkServiceExistsMutex.RUnlock()
	argsForCall := fake.checkServiceExistsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeMigrator) CheckServiceExistsReturns(result1 error) {
	fake.checkServiceExistsMutex.Lock()
	defer fake.checkServiceExistsMutex.Unlock()
	fake.CheckServiceExistsStub = nil
	fake.checkServiceExistsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMigrator) CheckServiceExistsReturnsOnCall(i int, result1 error) {
	fake.checkServiceExistsMutex.Lock()
	defer fake.checkServiceExistsMutex.Unlock()
	fake.CheckServiceExistsStub = nil
	if fake.checkServiceExistsReturnsOnCall == nil {
		fake.checkServiceExistsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.checkServiceExistsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeMigrator) ConfigureServiceInstance(arg1 string) error {
	fake.configureServiceInstanceMutex.Lock()
	ret, specificReturn := fake.configureServiceInstanceReturnsOnCall[len(fake.configureServiceInstanceArgsForCall)]
	fake.configureServiceInstanceArgsForCall = append(fake.configureServiceInstanceArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("ConfigureServiceInstance", []interface{}{arg1})
	fake.configureServiceInstanceMutex.Unlock()
	if fake.ConfigureServiceInstanceStub != nil {
		return fake.ConfigureServiceInstanceStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.configureServiceInstanceReturns
	return fakeReturns.result1
}

func (fake *FakeMigrator) ConfigureServiceInstanceCallCount() int {
	fake.configureServiceInstanceMutex.RLock()
	defer fake.configureServiceInstanceMutex.RUnlock()
	return len(fake.configureServiceInstanceArgsForCall)
}

func (fake *FakeMigrator) ConfigureServiceInstanceCalls(stub func(string) error) {
	fake.configureServiceInstanceMutex.Lock()
	defer fake.configureServiceInstanceMutex.Unlock()
	fake.ConfigureServiceInstanceStub = stub
}

func (fake *FakeMigrator) ConfigureServiceInstanceArgsForCall(i int) string {
	fake.configureServiceInstanceMutex.RLock()
	defer fake.configureServiceInstanceMutex.RUnlock()
	argsForCall := fake.configureServiceInstanceArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeMigrator) ConfigureServiceInstanceReturns(result1 error) {
	fake.configureServiceInstanceMutex.Lock()
	defer fake.configureServiceInstanceMutex.Unlock()
	fake.ConfigureServiceInstanceStub = nil
	fake.configureServiceInstanceReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMigrator) ConfigureServiceInstanceReturnsOnCall(i int, result1 error) {
	fake.configureServiceInstanceMutex.Lock()
	defer fake.configureServiceInstanceMutex.Unlock()
	fake.ConfigureServiceInstanceStub = nil
	if fake.configureServiceInstanceReturnsOnCall == nil {
		fake.configureServiceInstanceReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.configureServiceInstanceReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeMigrator) CreateAndConfigureServiceInstance(arg1 string, arg2 string) error {
	fake.createAndConfigureServiceInstanceMutex.Lock()
	ret, specificReturn := fake.createAndConfigureServiceInstanceReturnsOnCall[len(fake.createAndConfigureServiceInstanceArgsForCall)]
	fake.createAndConfigureServiceInstanceArgsForCall = append(fake.createAndConfigureServiceInstanceArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	fake.recordInvocation("CreateAndConfigureServiceInstance", []interface{}{arg1, arg2})
	fake.createAndConfigureServiceInstanceMutex.Unlock()
	if fake.CreateAndConfigureServiceInstanceStub != nil {
		return fake.CreateAndConfigureServiceInstanceStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.createAndConfigureServiceInstanceReturns
	return fakeReturns.result1
}

func (fake *FakeMigrator) CreateAndConfigureServiceInstanceCallCount() int {
	fake.createAndConfigureServiceInstanceMutex.RLock()
	defer fake.createAndConfigureServiceInstanceMutex.RUnlock()
	return len(fake.createAndConfigureServiceInstanceArgsForCall)
}

func (fake *FakeMigrator) CreateAndConfigureServiceInstanceCalls(stub func(string, string) error) {
	fake.createAndConfigureServiceInstanceMutex.Lock()
	defer fake.createAndConfigureServiceInstanceMutex.Unlock()
	fake.CreateAndConfigureServiceInstanceStub = stub
}

func (fake *FakeMigrator) CreateAndConfigureServiceInstanceArgsForCall(i int) (string, string) {
	fake.createAndConfigureServiceInstanceMutex.RLock()
	defer fake.createAndConfigureServiceInstanceMutex.RUnlock()
	argsForCall := fake.createAndConfigureServiceInstanceArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeMigrator) CreateAndConfigureServiceInstanceReturns(result1 error) {
	fake.createAndConfigureServiceInstanceMutex.Lock()
	defer fake.createAndConfigureServiceInstanceMutex.Unlock()
	fake.CreateAndConfigureServiceInstanceStub = nil
	fake.createAndConfigureServiceInstanceReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMigrator) CreateAndConfigureServiceInstanceReturnsOnCall(i int, result1 error) {
	fake.createAndConfigureServiceInstanceMutex.Lock()
	defer fake.createAndConfigureServiceInstanceMutex.Unlock()
	fake.CreateAndConfigureServiceInstanceStub = nil
	if fake.createAndConfigureServiceInstanceReturnsOnCall == nil {
		fake.createAndConfigureServiceInstanceReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createAndConfigureServiceInstanceReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeMigrator) DeleteServiceInstanceOnError(arg1 string) error {
	fake.deleteServiceInstanceOnErrorMutex.Lock()
	ret, specificReturn := fake.deleteServiceInstanceOnErrorReturnsOnCall[len(fake.deleteServiceInstanceOnErrorArgsForCall)]
	fake.deleteServiceInstanceOnErrorArgsForCall = append(fake.deleteServiceInstanceOnErrorArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("DeleteServiceInstanceOnError", []interface{}{arg1})
	fake.deleteServiceInstanceOnErrorMutex.Unlock()
	if fake.DeleteServiceInstanceOnErrorStub != nil {
		return fake.DeleteServiceInstanceOnErrorStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.deleteServiceInstanceOnErrorReturns
	return fakeReturns.result1
}

func (fake *FakeMigrator) DeleteServiceInstanceOnErrorCallCount() int {
	fake.deleteServiceInstanceOnErrorMutex.RLock()
	defer fake.deleteServiceInstanceOnErrorMutex.RUnlock()
	return len(fake.deleteServiceInstanceOnErrorArgsForCall)
}

func (fake *FakeMigrator) DeleteServiceInstanceOnErrorCalls(stub func(string) error) {
	fake.deleteServiceInstanceOnErrorMutex.Lock()
	defer fake.deleteServiceInstanceOnErrorMutex.Unlock()
	fake.DeleteServiceInstanceOnErrorStub = stub
}

func (fake *FakeMigrator) DeleteServiceInstanceOnErrorArgsForCall(i int) string {
	fake.deleteServiceInstanceOnErrorMutex.RLock()
	defer fake.deleteServiceInstanceOnErrorMutex.RUnlock()
	argsForCall := fake.deleteServiceInstanceOnErrorArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeMigrator) DeleteServiceInstanceOnErrorReturns(result1 error) {
	fake.deleteServiceInstanceOnErrorMutex.Lock()
	defer fake.deleteServiceInstanceOnErrorMutex.Unlock()
	fake.DeleteServiceInstanceOnErrorStub = nil
	fake.deleteServiceInstanceOnErrorReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMigrator) DeleteServiceInstanceOnErrorReturnsOnCall(i int, result1 error) {
	fake.deleteServiceInstanceOnErrorMutex.Lock()
	defer fake.deleteServiceInstanceOnErrorMutex.Unlock()
	fake.DeleteServiceInstanceOnErrorStub = nil
	if fake.deleteServiceInstanceOnErrorReturnsOnCall == nil {
		fake.deleteServiceInstanceOnErrorReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteServiceInstanceOnErrorReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeMigrator) MigrateData(arg1 migrate.MigrateOptions) error {
	fake.migrateDataMutex.Lock()
	ret, specificReturn := fake.migrateDataReturnsOnCall[len(fake.migrateDataArgsForCall)]
	fake.migrateDataArgsForCall = append(fake.migrateDataArgsForCall, struct {
		arg1 migrate.MigrateOptions
	}{arg1})
	fake.recordInvocation("MigrateData", []interface{}{arg1})
	fake.migrateDataMutex.Unlock()
	if fake.MigrateDataStub != nil {
		return fake.MigrateDataStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.migrateDataReturns
	return fakeReturns.result1
}

func (fake *FakeMigrator) MigrateDataCallCount() int {
	fake.migrateDataMutex.RLock()
	defer fake.migrateDataMutex.RUnlock()
	return len(fake.migrateDataArgsForCall)
}

func (fake *FakeMigrator) MigrateDataCalls(stub func(migrate.MigrateOptions) error) {
	fake.migrateDataMutex.Lock()
	defer fake.migrateDataMutex.Unlock()
	fake.MigrateDataStub = stub
}

func (fake *FakeMigrator) MigrateDataArgsForCall(i int) migrate.MigrateOptions {
	fake.migrateDataMutex.RLock()
	defer fake.migrateDataMutex.RUnlock()
	argsForCall := fake.migrateDataArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeMigrator) MigrateDataReturns(result1 error) {
	fake.migrateDataMutex.Lock()
	defer fake.migrateDataMutex.Unlock()
	fake.MigrateDataStub = nil
	fake.migrateDataReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMigrator) MigrateDataReturnsOnCall(i int, result1 error) {
	fake.migrateDataMutex.Lock()
	defer fake.migrateDataMutex.Unlock()
	fake.MigrateDataStub = nil
	if fake.migrateDataReturnsOnCall == nil {
		fake.migrateDataReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.migrateDataReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeMigrator) RenameServiceInstances(arg1 string, arg2 string) error {
	fake.renameServiceInstancesMutex.Lock()
	ret, specificReturn := fake.renameServiceInstancesReturnsOnCall[len(fake.renameServiceInstancesArgsForCall)]
	fake.renameServiceInstancesArgsForCall = append(fake.renameServiceInstancesArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	fake.recordInvocation("RenameServiceInstances", []interface{}{arg1, arg2})
	fake.renameServiceInstancesMutex.Unlock()
	if fake.RenameServiceInstancesStub != nil {
		return fake.RenameServiceInstancesStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.renameServiceInstancesReturns
	return fakeReturns.result1
}

func (fake *FakeMigrator) RenameServiceInstancesCallCount() int {
	fake.renameServiceInstancesMutex.RLock()
	defer fake.renameServiceInstancesMutex.RUnlock()
	return len(fake.renameServiceInstancesArgsForCall)
}

func (fake *FakeMigrator) RenameServiceInstancesCalls(stub func(string, string) error) {
	fake.renameServiceInstancesMutex.Lock()
	defer fake.renameServiceInstancesMutex.Unlock()
	fake.RenameServiceInstancesStub = stub
}

func (fake *FakeMigrator) RenameServiceInstancesArgsForCall(i int) (string, string) {
	fake.renameServiceInstancesMutex.RLock()
	defer fake.renameServiceInstancesMutex.RUnlock()
	argsForCall := fake.renameServiceInstancesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeMigrator) RenameServiceInstancesReturns(result1 error) {
	fake.renameServiceInstancesMutex.Lock()
	defer fake.renameServiceInstancesMutex.Unlock()
	fake.RenameServiceInstancesStub = nil
	fake.renameServiceInstancesReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMigrator) RenameServiceInstancesReturnsOnCall(i int, result1 error) {
	fake.renameServiceInstancesMutex.Lock()
	defer fake.renameServiceInstancesMutex.Unlock()
	fake.RenameServiceInstancesStub = nil
	if fake.renameServiceInstancesReturnsOnCall == nil {
		fake.renameServiceInstancesReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.renameServiceInstancesReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeMigrator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.checkServiceExistsMutex.RLock()
	defer fake.checkServiceExistsMutex.RUnlock()
	fake.configureServiceInstanceMutex.RLock()
	defer fake.configureServiceInstanceMutex.RUnlock()
	fake.createAndConfigureServiceInstanceMutex.RLock()
	defer fake.createAndConfigureServiceInstanceMutex.RUnlock()
	fake.deleteServiceInstanceOnErrorMutex.RLock()
	defer fake.deleteServiceInstanceOnErrorMutex.RUnlock()
	fake.migrateDataMutex.RLock()
	defer fake.migrateDataMutex.RUnlock()
	fake.renameServiceInstancesMutex.RLock()
	defer fake.renameServiceInstancesMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeMigrator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ plugin.Migrator = new(FakeMigrator)
