#!/usr/bin/env bash

#docker run -v $PWD:$PWD -t percona-server echo 'hello world
# wget boost_1_59_0.tar.gz
# apt-get install cmake wget g++ libaio-dev
mkdir build
wget -O /tmp/percona-server.tgz https://www.percona.com/downloads/Percona-Server-LATEST/Percona-Server-5.7.21-20/source/tarball/percona-server-5.7.21-20.tar.gz
tar xzvf /tmp/percona-server.tgz
cd /tmp/percona-server-5.7.21-20
  CMAKE_INCLUDE_PATH=/usr/include/ cmake . \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DBUILD_CONFIG=mysql_release \
    -DFEATURE_SET=community \
    -DWITH_EMBEDDED_SERVER=OFF \
    -DCMAKE_INSTALL_PREFIX=./build \
    -DWITH_BOOST=../boost_1_59_0 \
    -DWITH_ROCKSDB=off \
    -DWITH_SSL=system \
    -DINSTALL_MYSQLTESTDIR= \
    -DWITHOUT_SERVER=ON
  make --jobs 4
  make install
