#!/usr/bin/env bash

# Copyright (C) 2018-Present Pivotal Software, Inc. All rights reserved.
#
# This program and the accompanying materials are made available under the terms of the under the Apache License,
# Version 2.0 (the "License”); you may not use this file except in compliance with the License. You may obtain a copy
# of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
# an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.

set -euo pipefail

bin_dir='app/bin'
lib_dir='app/lib'
percona_version='5.7.29-32'
percona_major_minor="5.7"

function install_mysql_client_utils() {
    local build_dir
    local build_deps=(
      cmake
      g++
      make
      libncurses5-dev
      libpam0g-dev
      libssl-dev
      zlib1g-dev
    )

    build_dir=$(mktemp -d)

    DEBIAN_FRONTEND=noninteractive apt-get update

    DEBIAN_FRONTEND=noninteractive apt-get -y \
        install --no-install-recommends "${build_deps[@]}"

    curl -Ls "http://jenkins.percona.com/downloads/boost/boost_1_59_0.tar.gz" \
        > "${build_dir}/boost.tgz" \
        && sha256sum -c - <<< "47f11c8844e579d02691a607fbd32540104a9ac7a2534a8ddaef50daf502baac  ${build_dir}/boost.tgz"

    curl -Ls "https://www.percona.com/downloads/Percona-Server-${percona_major_minor}/Percona-Server-${percona_version}/source/tarball/percona-server-${percona_version}.tar.gz" \
        > "${build_dir}/percona.tgz" \
        && sha256sum -c - <<< "e3a7e6a0d966e41f62645f88cfbc75e052756f6ab45bd8b981343a0d9f5c3aa4  ${build_dir}/percona.tgz"

    tar -xf "${build_dir}/boost.tgz" -C "${build_dir}" && \
    tar -xf "${build_dir}/percona.tgz" -C "${build_dir}" && \

    pushd "${build_dir}/percona-server-${percona_version}" >/dev/null
    CXXFLAGS=-static-libstdc++ \
    CMAKE_INCLUDE_PATH=/usr/include/ \
    cmake . \
      -DBUILD_CONFIG=mysql_release \
      -DCMAKE_BUILD_TYPE=RelWithDebInfo \
      -DCMAKE_INSTALL_PREFIX=/home/vcap/app \
      -DCURSES_LIBRARY=/usr/lib/x86_64-linux-gnu/libtinfo.a \
      -DFEATURE_SET=community \
      -DIGNORE_AIO_CHECK=ON \
      -DINSTALL_MYSQLTESTDIR= \
      -DWITH_BOOST="../boost_1_59_0" \
      -DWITH_EDITLINE=bundled \
      -DWITH_EMBEDDED_SERVER=OFF \
      -DWITH_PAM=on \
      -DWITH_RAPID=OFF \
      -DWITH_ROCKSDB=OFF \
      -DWITH_SSL=/usr \
      -DWITH_TOKUDB=OFF \
      -DWITH_ZLIB=system \
      && make --jobs 4 \
      && make install
    popd >/dev/null

    echo "PWD = $PWD"
    ls -lthr "$PWD"
    install -D /home/vcap/app/LICENSE "$PWD/app/LICENSE"
    install -D /home/vcap/app/README "$PWD/app/README"
    install -D /home/vcap/app/bin/mysql "$PWD/app/bin/mysql"
    install -D /home/vcap/app/bin/mysqldump "$PWD/app/bin/mysqldump"
    install -D /home/vcap/app/lib/mysql/plugin/dialog.so "$PWD/app/lib/mysql/plugin/dialog.so"
}

function install_migrate_task() {
    curl --silent https://dl.google.com/go/go1.10.4.linux-amd64.tar.gz > /tmp/golang.tgz \
        && sha256sum -c - <<< "fa04efdb17a275a0c6e137f969a1c4eb878939e91e1da16060ce42f02c2ec5ec /tmp/golang.tgz" \
        && tar -xf /tmp/golang.tgz -C /usr/local/

    GOROOT=/usr/local/go
    PATH="$PATH:$GOROOT/bin"
    GOPATH="$(mktemp -d)"
    export GOPATH GOROOT PATH

    mkdir -p "${GOPATH}/src/github.com/pivotal-cf/mysql-cli-plugin/"
    cp -a . "${GOPATH}/src/github.com/pivotal-cf/mysql-cli-plugin/"

    GOBIN="$PWD/app/bin" go install github.com/pivotal-cf/mysql-cli-plugin/tasks/migrate
}

function clean_app_directory() {
    rm -rf ${bin_dir}
    rm -rf ${lib_dir}
    mkdir -p ${bin_dir}
    mkdir -p ${lib_dir}
}

function main() {
    >&2 echo "Cleaning app/ directory..."
    clean_app_directory
    >&2 echo "Installing migrate task binary into app/"
    install_migrate_task
    >&2 echo "Installing mysql client utilities into app/"
    install_mysql_client_utils
}

main
