#!/usr/bin/env bash

# Copyright (C) 2018-Present Pivotal Software, Inc. All rights reserved.
#
# This program and the accompanying materials are made available under the terms of the under the Apache License,
# Version 2.0 (the "License”); you may not use this file except in compliance with the License. You may obtain a copy
# of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
# an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.


set -euo pipefail

SCRIPT_DIR=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)
ROOT_DIR=$(cd "${SCRIPT_DIR}/.." && pwd)
VERSION="${VERSION:-0.0.1}"

cd "${ROOT_DIR}"

>&2 echo "Downloading packr..."
go get -u github.com/gobuffalo/packr/...

>&2 echo "Building app assets..."
docker run --rm -v "$PWD:$PWD" -w "$PWD" -t cloudfoundry/cflinuxfs3 ./scripts/build-assets

>&2 echo "Running go generate ./... to repack app assets..."
go generate ./...

>&2 echo "Building $PWD/mysql-cli-plugin"
go build \
    -tags forceposix \
    -ldflags="-X 'github.com/pivotal-cf/mysql-cli-plugin/mysql-tools/plugin.version=${VERSION}'" \
    -o mysql-cli-plugin \
    .

>&2 echo "Done!"
