#!/usr/bin/env bash

# Copyright (C) 2018-Present Pivotal Software, Inc. All rights reserved.
#
# This program and the accompanying materials are made available under the terms of the under the Apache License,
# Version 2.0 (the "License”); you may not use this file except in compliance with the License. You may obtain a copy
# of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
# an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.

set -e

tmp_dir=$(mktemp -d)
output_dir='app/assets'
boost_version='1_59_0'
percona_version='5.7.21-20'

DEBIAN_FRONTEND=noninteractive apt-get update && \
DEBIAN_FRONTEND=noninteractive apt-get -y install \
  --no-install-recommends \
  cmake g++ make \
  libreadline6-dev \
  libncurses5-dev \
  libssl-dev \
  zlib1g-dev

wget -O $tmp_dir/boost.tgz http://jenkins.percona.com/downloads/boost/boost_${boost_version}.tar.gz
wget -O $tmp_dir/percona.tgz https://www.percona.com/downloads/Percona-Server-LATEST/Percona-Server-${percona_version}/source/tarball/percona-server-${percona_version}.tar.gz

tar -xf $tmp_dir/boost.tgz -C $tmp_dir && \
tar -xf $tmp_dir/percona.tgz -C $tmp_dir && \

pushd $tmp_dir/percona-server-${percona_version} >/dev/null
CMAKE_INCLUDE_PATH=/usr/include/ cmake . \
  -DBUILD_CONFIG=mysql_release \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DCMAKE_INSTALL_PREFIX=/build \
  -DFEATURE_SET=community \
  -DINSTALL_MYSQLTESTDIR= \
  -DWITH_BOOST=../boost_${boost_version} \
  -DWITH_EMBEDDED_SERVER=OFF \
  -DWITH_READLINE=system \
  -DWITH_SSL=system \
  -DWITH_ZLIB=system \
  -DIGNORE_AIO_CHECK=ON \
  -DWITHOUT_SERVER=ON && \
  make --jobs 4 && \
  make install
popd >/dev/null

rm -rf ${output_dir}
mkdir -p ${output_dir}
mv /build/COPYING ${output_dir}
mv /build/README.MySQL ${output_dir}
mv /build/bin/mysql ${output_dir}
mv /build/bin/mysqldump ${output_dir}