#!/usr/bin/env bash

# Copyright (C) 2018-Present Pivotal Software, Inc. All rights reserved.
#
# This program and the accompanying materials are made available under the terms of the under the Apache License,
# Version 2.0 (the "License”); you may not use this file except in compliance with the License. You may obtain a copy
# of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
# an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.

set -o errexit -o nounset -o pipefail

topdir=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

: "${VERSION:=0.0.1}"
: "${DOCKER_DEFAULT_PLATFORM:=linux/amd64}"
: "${GIT_SHA:=$(git -C "$topdir" rev-parse --short HEAD)}"

export DOCKER_DEFAULT_PLATFORM

run() {
  echo >&2 "\$ $*"
  "$@"
}

cd "${topdir}"

docker_image=$(run docker build -q -f scripts/Dockerfile .)

echo >&2 "Building app assets..."
run docker run --rm \
  --mount=type=volume,src=percona-build-cache,dst=/build \
  --mount=type=volume,src=gomod-cache,dst=/go \
  --mount=type="bind,src=$PWD,dst=/workspace" \
  --workdir=/workspace \
  --tty \
  "${docker_image}" \
  ./scripts/build-assets

echo >&2 "Building $PWD/mysql-cli-plugin"
run go build \
  -tags forceposix \
  -ldflags="-s -w
            -X 'github.com/pivotal-cf/mysql-cli-plugin/version.Version=${VERSION}'
            -X 'github.com/pivotal-cf/mysql-cli-plugin/version.GitSHA=${GIT_SHA}'" \
  -o mysql-cli-plugin \
  .

echo >&2 "Done!"
