#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail

topdir=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

cd "$topdir"

GINKGO="go run github.com/onsi/ginkgo/ginkgo"

${GINKGO} -skipPackage=specs -r "$@" *